/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "claim" | "deals" | "lock" | "nextId" | "refund"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "Locked" | "Refunded"): EventFragment;

    encodeFunctionData(functionFragment: 'claim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lock', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextId', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [id: BigNumberish, provider: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, provider: string, amount: bigint];
      export interface OutputObject {id: bigint, provider: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockedEvent {
      export type InputTuple = [id: BigNumberish, payer: AddressLike, provider: AddressLike, amount: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, payer: string, provider: string, amount: bigint, deadline: bigint];
      export interface OutputObject {id: bigint, payer: string, provider: string, amount: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [id: BigNumberish, payer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, payer: string, amount: bigint];
      export interface OutputObject {id: bigint, payer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claim: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint] & {payer: string, provider: string, amount: bigint, deadline: bigint }],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [provider: AddressLike, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    nextId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint] & {payer: string, provider: string, amount: bigint, deadline: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [provider: AddressLike, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'nextId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'Locked'): TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;

    filters: {
      
      'Claimed(uint256,address,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'Locked(uint256,address,address,uint256,uint64)': TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
      Locked: TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
    

      'Refunded(uint256,address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    
    };
  }